// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorApp.API.Data;

#nullable disable

namespace TutorApp.API.Migrations
{
    [DbContext(typeof(TutorDbContext))]
    [Migration("20260202221904_AzMigration")]
    partial class AzMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TutorApp.API.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTutor")
                        .HasColumnType("bit");

                    b.HasKey("Username");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("TutorApp.API.Models.AccountHistory", b =>
                {
                    b.Property<int>("HistoryEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryEventID"));

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.HasKey("HistoryEventID");

                    b.HasIndex("AccountUsername");

                    b.ToTable("AccountHistory");
                });

            modelBuilder.Entity("TutorApp.API.Models.AccountSettings", b =>
                {
                    b.Property<string>("AccountUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePictureFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountUsername");

                    b.ToTable("AccountSettings");
                });

            modelBuilder.Entity("TutorApp.API.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerSession")
                        .HasColumnType("money");

                    b.Property<string>("TutorUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CourseID");

                    b.HasIndex("TutorUsername");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("TutorApp.API.Models.HomeworkAssignment", b =>
                {
                    b.Property<int>("HomeworkAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeworkAssignmentID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<string>("SolutionFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HomeworkAssignmentID");

                    b.HasIndex("SessionID");

                    b.ToTable("HomeworkAssignment");
                });

            modelBuilder.Entity("TutorApp.API.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageID");

                    b.HasIndex("RecipientUsername");

                    b.HasIndex("SenderUsername");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("TutorApp.API.Models.Note", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteID"));

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("NoteID");

                    b.HasIndex("AccountUsername");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("TutorApp.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("AccountUsername");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("TutorApp.API.Models.PaymentRecord", b =>
                {
                    b.Property<int>("PaymentRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentRecordID"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("money");

                    b.Property<int>("MeansOfPayment")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TutorUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentRecordID");

                    b.HasIndex("StudentUsername");

                    b.HasIndex("TutorUsername");

                    b.ToTable("PaymentRecord");
                });

            modelBuilder.Entity("TutorApp.API.Models.Session", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int>("ConfirmationStatus")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaidFor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SessionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SessionID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentUsername");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("TutorApp.API.Models.Student_Course", b =>
                {
                    b.Property<string>("StudentUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentUsername", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("TutorApp.API.Models.TeachingMaterial", b =>
                {
                    b.Property<int>("TeachingMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeachingMaterialID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeachingMaterialID");

                    b.HasIndex("CourseID");

                    b.ToTable("TeachingMaterial");
                });

            modelBuilder.Entity("TutorApp.API.Models.AccountHistory", b =>
                {
                    b.HasOne("TutorApp.API.Models.Account", "Account")
                        .WithMany("AccountHistory")
                        .HasForeignKey("AccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TutorApp.API.Models.AccountSettings", b =>
                {
                    b.HasOne("TutorApp.API.Models.Account", "Account")
                        .WithOne("AccountSettings")
                        .HasForeignKey("TutorApp.API.Models.AccountSettings", "AccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TutorApp.API.Models.Course", b =>
                {
                    b.HasOne("TutorApp.API.Models.Account", "Tutor")
                        .WithMany("TutoredCourses")
                        .HasForeignKey("TutorUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorApp.API.Models.HomeworkAssignment", b =>
                {
                    b.HasOne("TutorApp.API.Models.Session", "Session")
                        .WithMany("HomeworkAssignments")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TutorApp.API.Models.Message", b =>
                {
                    b.HasOne("TutorApp.API.Models.Account", "Recipient")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("RecipientUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutorApp.API.Models.Account", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TutorApp.API.Models.Note", b =>
                {
                    b.HasOne("TutorApp.API.Models.Account", "Account")
                        .WithMany("Notes")
                        .HasForeignKey("AccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TutorApp.API.Models.Notification", b =>
                {
                    b.HasOne("TutorApp.API.Models.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TutorApp.API.Models.PaymentRecord", b =>
                {
                    b.HasOne("TutorApp.API.Models.Account", "Student")
                        .WithMany("PaymentsMade")
                        .HasForeignKey("StudentUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutorApp.API.Models.Account", "Tutor")
                        .WithMany("PaymentsReceived")
                        .HasForeignKey("TutorUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorApp.API.Models.Session", b =>
                {
                    b.HasOne("TutorApp.API.Models.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorApp.API.Models.Account", "Student")
                        .WithMany("Sessions")
                        .HasForeignKey("StudentUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorApp.API.Models.Student_Course", b =>
                {
                    b.HasOne("TutorApp.API.Models.Course", "Course")
                        .WithMany("EnrolledStudents")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutorApp.API.Models.Account", "Student")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("StudentUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorApp.API.Models.TeachingMaterial", b =>
                {
                    b.HasOne("TutorApp.API.Models.Course", "Course")
                        .WithMany("TeachingMaterials")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TutorApp.API.Models.Account", b =>
                {
                    b.Navigation("AccountHistory");

                    b.Navigation("AccountSettings")
                        .IsRequired();

                    b.Navigation("EnrolledCourses");

                    b.Navigation("Notes");

                    b.Navigation("Notifications");

                    b.Navigation("PaymentsMade");

                    b.Navigation("PaymentsReceived");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("Sessions");

                    b.Navigation("TutoredCourses");
                });

            modelBuilder.Entity("TutorApp.API.Models.Course", b =>
                {
                    b.Navigation("EnrolledStudents");

                    b.Navigation("Sessions");

                    b.Navigation("TeachingMaterials");
                });

            modelBuilder.Entity("TutorApp.API.Models.Session", b =>
                {
                    b.Navigation("HomeworkAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
